/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.AgendaController;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author Ailton
 */
public class Agenda extends javax.swing.JFrame {

    private final AgendaController controller;

    /**
     * Creates new form Agenda
     */
    public Agenda() {
        initComponents();
        controller = new AgendaController(this);
        iniciar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlHora = new javax.swing.JLabel();
        Observacao = new javax.swing.JTextArea();
        Hora = new javax.swing.JTextField();
        jlData = new javax.swing.JLabel();
        Data = new javax.swing.JTextField();
        Valor = new javax.swing.JTextField();
        jlValor = new javax.swing.JLabel();
        jComboBoxServico = new javax.swing.JComboBox<>();
        glServico = new javax.swing.JLabel();
        jlID = new javax.swing.JLabel();
        jlCliente = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TabelaAgendamentos = new javax.swing.JTable();
        btAgendar = new javax.swing.JButton();
        jComboBoxCliente = new javax.swing.JComboBox<>();
        Id = new javax.swing.JTextField();
        jlAgenda = new javax.swing.JLabel();
        jtextObservacao = new javax.swing.JLabel();
        jlFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlHora.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jlHora.setForeground(new java.awt.Color(255, 255, 255));
        jlHora.setText("Hora");
        getContentPane().add(jlHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 530, -1, -1));

        Observacao.setColumns(20);
        Observacao.setRows(5);
        getContentPane().add(Observacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 230, 500, 280));
        getContentPane().add(Hora, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 530, 380, 40));

        jlData.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jlData.setForeground(new java.awt.Color(255, 255, 255));
        jlData.setText("Data");
        getContentPane().add(jlData, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 470, -1, -1));
        getContentPane().add(Data, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 470, 380, 40));
        getContentPane().add(Valor, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 410, 380, 40));

        jlValor.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jlValor.setForeground(new java.awt.Color(255, 255, 255));
        jlValor.setText("Valor");
        getContentPane().add(jlValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, -1, -1));

        jComboBoxServico.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxServicoItemStateChanged(evt);
            }
        });
        getContentPane().add(jComboBoxServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, 380, 40));

        glServico.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        glServico.setForeground(new java.awt.Color(255, 255, 255));
        glServico.setText("Serviço");
        getContentPane().add(glServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, -1, -1));

        jlID.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jlID.setForeground(new java.awt.Color(255, 255, 255));
        jlID.setText("Id");
        getContentPane().add(jlID, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, -1, -1));

        jlCliente.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jlCliente.setForeground(new java.awt.Color(255, 255, 255));
        jlCliente.setText("Cliente");
        getContentPane().add(jlCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, -1, -1));

        TabelaAgendamentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Cliente", "Servico", "Valor", "Data", "Hora", "Observação"
            }
        ));
        jScrollPane2.setViewportView(TabelaAgendamentos);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 610, 1070, 230));

        btAgendar.setBackground(new java.awt.Color(60, 233, 106));
        btAgendar.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        btAgendar.setForeground(java.awt.Color.green);
        btAgendar.setText("Agendar");
        btAgendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAgendarActionPerformed(evt);
            }
        });
        getContentPane().add(btAgendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 530, 500, 40));

        jComboBoxCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxClienteActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 380, 40));

        Id.setEditable(false);
        Id.setText("0");
        Id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdActionPerformed(evt);
            }
        });
        getContentPane().add(Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 380, 40));

        jlAgenda.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jlAgenda.setForeground(new java.awt.Color(255, 255, 255));
        jlAgenda.setText("Agenda");
        getContentPane().add(jlAgenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 140, -1, -1));

        jtextObservacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/Agenda-PainelFundo.png"))); // NOI18N
        getContentPane().add(jtextObservacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1450, 1080));

        jlFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/AgendaFundo.png"))); // NOI18N
        getContentPane().add(jlFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 1080));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdActionPerformed

    private void jComboBoxClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxClienteActionPerformed

    private void jComboBoxServicoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxServicoItemStateChanged
        // TODO add your handling code here:
        
        this.controller.atualizaValor();
    }//GEN-LAST:event_jComboBoxServicoItemStateChanged

    private void btAgendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAgendarActionPerformed
        // TODO add your handling code here:
        
        this.controller.agendar();
    }//GEN-LAST:event_btAgendarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Data;
    private javax.swing.JTextField Hora;
    private javax.swing.JTextField Id;
    private javax.swing.JTextArea Observacao;
    private javax.swing.JTable TabelaAgendamentos;
    private javax.swing.JTextField Valor;
    private javax.swing.JButton btAgendar;
    private javax.swing.JLabel glServico;
    private javax.swing.JComboBox<String> jComboBoxCliente;
    private javax.swing.JComboBox<String> jComboBoxServico;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jlAgenda;
    private javax.swing.JLabel jlCliente;
    private javax.swing.JLabel jlData;
    private javax.swing.JLabel jlFundo;
    private javax.swing.JLabel jlHora;
    private javax.swing.JLabel jlID;
    private javax.swing.JLabel jlValor;
    private javax.swing.JLabel jtextObservacao;
    // End of variables declaration//GEN-END:variables

    private void iniciar() {
        this.controller.atualizaTabela();
        this.controller.atualizaCliente();
        this.controller.atualizServico();
        this.controller.atualizaValor();
    }

    public JTable getTabelaAgendamentos() {
        return TabelaAgendamentos;
    }

    public void setTabelaAgendamentos(JTable TabelaAgendamentos) {
        this.TabelaAgendamentos = TabelaAgendamentos;
    }

    public JComboBox<String> getjComboBoxCliente() {
        return jComboBoxCliente;
    }

    public void setjComboBoxCliente(JComboBox<String> jComboBoxCliente) {
        this.jComboBoxCliente = jComboBoxCliente;
    }

    public JComboBox<String> getjComboBoxServico() {
        return jComboBoxServico;
    }

    public void setjComboBoxServico(JComboBox<String> jComboBoxServico) {
        this.jComboBoxServico = jComboBoxServico;
    }

    public JTextField getValor() {
        return Valor;
    }

    public void setValor(JTextField Valor) {
        this.Valor = Valor;
    }

    public JTextField getData() {
        return Data;
    }

    public void setData(JTextField Data) {
        this.Data = Data;
    }

    public JTextField getHora() {
        return Hora;
    }

    public void setHora(JTextField Hora) {
        this.Hora = Hora;
    }

    public JTextField getId() {
        return Id;
    }

    public void setId(JTextField Id) {
        this.Id = Id;
    }

    public JTextArea getObservacao() {
        return Observacao;
    }

    public void setObservacao(JTextArea Observacao) {
        this.Observacao = Observacao;
    }
    
    
    
    
} 
