/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;


import DAO.ConnectionFactory;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.PreparedStatement;

/**
 *
 * @author Ailton
 */
public class Cadastro extends javax.swing.JFrame {

    /**
     * Creates new form Cadastro
     */
    public Cadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btCadastrar = new javax.swing.JButton();
        TextUsuario = new javax.swing.JTextField();
        jlsenha = new javax.swing.JLabel();
        TextSenha = new javax.swing.JPasswordField();
        jlusuario = new javax.swing.JLabel();
        jllogin = new javax.swing.JLabel();
        jlLogo = new javax.swing.JLabel();
        jlCaixa = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btCadastrar.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        btCadastrar.setText("Cadastrar");
        btCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(btCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 920, 370, 70));

        TextUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(TextUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 730, 410, 40));

        jlsenha.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlsenha.setForeground(new java.awt.Color(255, 255, 255));
        jlsenha.setText("Senha");
        getContentPane().add(jlsenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 800, -1, 20));

        TextSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(TextSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 830, 410, 40));

        jlusuario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlusuario.setForeground(new java.awt.Color(255, 255, 255));
        jlusuario.setText("Usuario");
        getContentPane().add(jlusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 700, -1, -1));

        jllogin.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jllogin.setForeground(new java.awt.Color(255, 255, 255));
        jllogin.setText("Login");
        getContentPane().add(jllogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 610, -1, 60));

        jlLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/barbeariaPires.jpg"))); // NOI18N
        getContentPane().add(jlLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 0, -1, -1));

        jlCaixa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/painel-login.png"))); // NOI18N
        getContentPane().add(jlCaixa, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 574, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextUsuarioActionPerformed

    private void TextSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextSenhaActionPerformed

    private void btCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarActionPerformed
        
        Connection con = ConnectionFactory.getConnection();
        PreparedStatement stmt = null;
        
        String sql = "insert into usuario(usuario,senha) values('Joao','321')";
        
        try{
            stmt = con.prepareStatement(sql);
            stmt.executeUpdate();
            
        } catch (SQLException ex){
            System.out.println("Erro ao salvar os dados " + ex.toString());     
        } finally {
            ConnectionFactory.closeConnection(con, stmt);
    }
    }//GEN-LAST:event_btCadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField TextSenha;
    private javax.swing.JTextField TextUsuario;
    private javax.swing.JButton btCadastrar;
    private javax.swing.JLabel jlCaixa;
    private javax.swing.JLabel jlLogo;
    private javax.swing.JLabel jllogin;
    private javax.swing.JLabel jlsenha;
    private javax.swing.JLabel jlusuario;
    // End of variables declaration//GEN-END:variables
}
